### ISSUE TITLE
error: no applicable method for xmlChildren

### ISSUE THREAD

**Issue by aenieblas** [fdiwg/smt-shiny#6]
![image](https://github.com/fdiwg/smt-shiny/assets/33573363/65e22551-06aa-4d77-b403-11ad30bc873f)

Hello - i'm getting this error when trying to run the SMT v6 LBSPR (european anchovy example)

**Comment by tokami** [comment]
Addressed with an update of lbmsmt. Waiting for final checks when updated package is incorporated.
