### ISSUE TITLE
report download fails

### ISSUE THREAD

**Issue by aenieblas** [fdiwg/smt-shiny#7]
For LBI, downloading the zip works fine, but downloading the report gives this error:

![image](https://github.com/fdiwg/smt-shiny/assets/33573363/11703eda-a562-4b76-b606-87205279c63a)

LBSPR report downloads without error.

**Comment by tokami** [comment]
It works for me, which data set and settings did you use?

**Comment by aenieblas** [comment]
The LBI report fails to download for all three examples. See screenshot for European anchovy:

![image](https://github.com/fdiwg/smt-shiny/assets/33573363/77dff8e3-d8e9-4c54-b8b3-fb54a53e28df)

**Comment by eblondel** [comment]
Fix has been merged, released and deployed on the i-marine infrastructure (version 0.6.2). @aenieblas can you test and confirm it works now?

**Comment by aenieblas** [comment]
Tested and it works! Thanks both!
